server:
  port: 8093
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
spring:
  security:
    oauth2:
      introspection:
        clientId: internal-client
        clientSecret: "{cipher}7064708e6cd6eae25f1e2e620002184c0b0e39151c42d384af47967af1907fb8a4425b9f10b8d055856d056025c7acca"
        introspectionEndpoint: http://sinebot-oauth-server/oauth2/token-info